###
POST http://localhost:4010/api/modulo
content-type: application/json

{
  "modulo":"7", 
  "descripcion": "Modulo 7"
}

###
GET http://localhost:4010/api/modulo
# Authorization: token xxx
# ?query1=aksdskamd
# &query2=aksdskamd


###
GET http://localhost:4010/api/modulo/1